name: IG Username Monitor
on:
  schedule:
    - cron: "*/5 * * * *"   # كل 5 دقايق
  workflow_dispatch: {}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - name: Run monitor
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          USERNAMES: ${{ vars.USERNAMES }}
        run: python ig-monitor.py
